// Malaysian Postcode to State/District mapping
export const MALAYSIAN_POSTCODE_MAP: Record<string, { state: string; district: string }> = {
  // Kuala Lumpur
  "50000": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50050": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50100": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50150": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50200": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50250": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50300": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50350": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50400": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50450": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50500": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50550": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50600": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50650": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50700": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50750": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50800": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50850": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50900": { state: "Kuala Lumpur", district: "Kuala Lumpur" },
  "50920": { state: "Kuala Lumpur", district: "Kuala Lumpur" },

  // Selangor
  "40000": { state: "Selangor", district: "Shah Alam" },
  "40100": { state: "Selangor", district: "Shah Alam" },
  "40150": { state: "Selangor", district: "Shah Alam" },
  "40160": { state: "Selangor", district: "Shah Alam" },
  "40170": { state: "Selangor", district: "Shah Alam" },
  "40200": { state: "Selangor", district: "Petaling Jaya" },
  "40300": { state: "Selangor", district: "Petaling Jaya" },
  "40400": { state: "Selangor", district: "Shah Alam" },
  "40450": { state: "Selangor", district: "Shah Alam" },
  "40500": { state: "Selangor", district: "Shah Alam" },
  "40550": { state: "Selangor", district: "Shah Alam" },
  "40560": { state: "Selangor", district: "Shah Alam" },
  "40570": { state: "Selangor", district: "Shah Alam" },
  "40572": { state: "Selangor", district: "Shah Alam" },
  "40576": { state: "Selangor", district: "Shah Alam" },
  "40800": { state: "Selangor", district: "Klang" },
  "40900": { state: "Selangor", district: "Klang" },
  "41000": { state: "Selangor", district: "Klang" },
  "41100": { state: "Selangor", district: "Klang" },
  "41200": { state: "Selangor", district: "Klang" },
  "41300": { state: "Selangor", district: "Selayang" },
  "41400": { state: "Selangor", district: "Selayang" },
  "41500": { state: "Selangor", district: "Ampang" },
  "41600": { state: "Selangor", district: "Ampang" },
  "41700": { state: "Selangor", district: "Ampang" },
  "41800": { state: "Selangor", district: "Ampang" },
  "41900": { state: "Selangor", district: "Ampang" },
  "42000": { state: "Selangor", district: "Puchong" },
  "42100": { state: "Selangor", district: "Puchong" },
  "42200": { state: "Selangor", district: "Puchong" },
  "42300": { state: "Selangor", district: "Puchong" },
  "42500": { state: "Selangor", district: "Sunway" },
  "42600": { state: "Selangor", district: "Subang Jaya" },
  "42700": { state: "Selangor", district: "Subang Jaya" },
  "42800": { state: "Selangor", district: "Subang Jaya" },
  "42900": { state: "Selangor", district: "Subang Jaya" },
  "43000": { state: "Selangor", district: "Kajang" },
  "43100": { state: "Selangor", district: "Kajang" },
  "43200": { state: "Selangor", district: "Kajang" },
  "43300": { state: "Selangor", district: "Kajang" },
  "43500": { state: "Selangor", district: "Serdang" },
  "43600": { state: "Selangor", district: "Serdang" },
  "43650": { state: "Selangor", district: "Serdang" },
  "43700": { state: "Selangor", district: "Sungai Petani" },
  "43800": { state: "Selangor", district: "Rawang" },
  "43900": { state: "Selangor", district: "Rawang" },
  "44000": { state: "Selangor", district: "Kuala Selangor" },
  "44100": { state: "Selangor", district: "Kuala Selangor" },
  "44200": { state: "Selangor", district: "Tanjung Karang" },
  "44300": { state: "Selangor", district: "Tanjung Karang" },
  "45000": { state: "Selangor", district: "Kuala Lumpur" },
  "45100": { state: "Selangor", district: "Kuala Lumpur" },

  // Johor
  "79000": { state: "Johor", district: "Johor Bahru" },
  "80000": { state: "Johor", district: "Johor Bahru" },
  "80100": { state: "Johor", district: "Johor Bahru" },
  "80200": { state: "Johor", district: "Johor Bahru" },
  "80300": { state: "Johor", district: "Johor Bahru" },
  "80400": { state: "Johor", district: "Johor Bahru" },
  "80500": { state: "Johor", district: "Johor Bahru" },
  "80600": { state: "Johor", district: "Johor Bahru" },
  "80700": { state: "Johor", district: "Johor Bahru" },
  "80800": { state: "Johor", district: "Johor Bahru" },
  "81000": { state: "Johor", district: "Kulai" },
  "81100": { state: "Johor", district: "Kulai" },
  "81200": { state: "Johor", district: "Kulai" },
  "81300": { state: "Johor", district: "Kulai" },
  "81400": { state: "Johor", district: "Pontian" },
  "82000": { state: "Johor", district: "Muar" },
  "82100": { state: "Johor", district: "Muar" },
  "82500": { state: "Johor", district: "Batu Pahat" },
  "82600": { state: "Johor", district: "Batu Pahat" },
  "83000": { state: "Johor", district: "Kluang" },
  "83100": { state: "Johor", district: "Kluang" },
  "84000": { state: "Johor", district: "Mersing" },
  "86000": { state: "Johor", district: "Kota Tinggi" },

  // Penang
  "10000": { state: "Penang", district: "Georgetown" },
  "10100": { state: "Penang", district: "Georgetown" },
  "10150": { state: "Penang", district: "Georgetown" },
  "10200": { state: "Penang", district: "Georgetown" },
  "10250": { state: "Penang", district: "Georgetown" },
  "10300": { state: "Penang", district: "Georgetown" },
  "10400": { state: "Penang", district: "Georgetown" },
  "10500": { state: "Penang", district: "Georgetown" },
  "10550": { state: "Penang", district: "Georgetown" },
  "10560": { state: "Penang", district: "Georgetown" },
  "10570": { state: "Penang", district: "Georgetown" },
  "10600": { state: "Penang", district: "Georgetown" },
  "10650": { state: "Penang", district: "Georgetown" },
  "10670": { state: "Penang", district: "Georgetown" },
  "10690": { state: "Penang", district: "Georgetown" },
  "10700": { state: "Penang", district: "Georgetown" },
  "10750": { state: "Penang", district: "Georgetown" },
  "10800": { state: "Penang", district: "Georgetown" },
  "10810": { state: "Penang", district: "Georgetown" },
  "10820": { state: "Penang", district: "Georgetown" },
  "10860": { state: "Penang", district: "Georgetown" },
  "11000": { state: "Penang", district: "Penang Island" },
  "11100": { state: "Penang", district: "Penang Island" },
  "11200": { state: "Penang", district: "Penang Island" },
  "11700": { state: "Penang", district: "Butterworth" },
  "11800": { state: "Penang", district: "Butterworth" },
  "12000": { state: "Penang", district: "Butterworth" },
  "12100": { state: "Penang", district: "Butterworth" },
  "13000": { state: "Penang", district: "Bukit Mertajam" },
  "13100": { state: "Penang", district: "Bukit Mertajam" },
  "13200": { state: "Penang", district: "Bukit Mertajam" },

  // Kedah
  "05000": { state: "Kedah", district: "Alor Setar" },
  "05100": { state: "Kedah", district: "Alor Setar" },
  "05200": { state: "Kedah", district: "Alor Setar" },
  "05250": { state: "Kedah", district: "Alor Setar" },
  "05350": { state: "Kedah", district: "Bandar Baharu" },
  "06000": { state: "Kedah", district: "Sungai Petani" },
  "06100": { state: "Kedah", district: "Sungai Petani" },
  "06200": { state: "Kedah", district: "Sungai Petani" },
  "06300": { state: "Kedah", district: "Kuala Kedah" },
  "07000": { state: "Kedah", district: "Langkawi" },
  "07100": { state: "Kedah", district: "Langkawi" },
  "07200": { state: "Kedah", district: "Langkawi" },
  "09000": { state: "Kedah", district: "Kota Setar" },

  // Perak
  "30000": { state: "Perak", district: "Ipoh" },
  "30100": { state: "Perak", district: "Ipoh" },
  "30200": { state: "Perak", district: "Ipoh" },
  "30250": { state: "Perak", district: "Ipoh" },
  "30300": { state: "Perak", district: "Ipoh" },
  "30350": { state: "Perak", district: "Ipoh" },
  "30400": { state: "Perak", district: "Ipoh" },
  "30450": { state: "Perak", district: "Ipoh" },
  "30500": { state: "Perak", district: "Ipoh" },
  "30550": { state: "Perak", district: "Ipoh" },
  "30600": { state: "Perak", district: "Ipoh" },
  "30650": { state: "Perak", district: "Ipoh" },
  "30700": { state: "Perak", district: "Ipoh" },
  "30750": { state: "Perak", district: "Ipoh" },
  "30800": { state: "Perak", district: "Ipoh" },
  "31000": { state: "Perak", district: "Tanjung Malim" },
  "33000": { state: "Perak", district: "Serendah" },
  "33100": { state: "Perak", district: "Serendah" },
  "34000": { state: "Perak", district: "Kuala Kubu Bharu" },
  "34100": { state: "Perak", district: "Kuala Kubu Bharu" },
  "34200": { state: "Perak", district: "Rawang" },
  "35000": { state: "Perak", district: "Taiping" },
  "35100": { state: "Perak", district: "Taiping" },
  "35200": { state: "Perak", district: "Taiping" },
  "35250": { state: "Perak", district: "Taiping" },
  "35300": { state: "Perak", district: "Taiping" },
  "35400": { state: "Perak", district: "Taiping" },

  // Kelantan
  "15000": { state: "Kelantan", district: "Kota Bharu" },
  "15050": { state: "Kelantan", district: "Kota Bharu" },
  "15100": { state: "Kelantan", district: "Kota Bharu" },
  "15150": { state: "Kelantan", district: "Kota Bharu" },
  "15160": { state: "Kelantan", district: "Kota Bharu" },
  "15170": { state: "Kelantan", district: "Kota Bharu" },
  "15200": { state: "Kelantan", district: "Kota Bharu" },
  "16000": { state: "Kelantan", district: "Tumpat" },
  "16100": { state: "Kelantan", district: "Tumpat" },
  "17000": { state: "Kelantan", district: "Machang" },
  "18000": { state: "Kelantan", district: "Pasir Mas" },
  "19000": { state: "Kelantan", district: "Tanah Merah" },

  // Terengganu
  "20000": { state: "Terengganu", district: "Kuala Terengganu" },
  "20100": { state: "Terengganu", district: "Kuala Terengganu" },
  "20200": { state: "Terengganu", district: "Kuala Terengganu" },
  "20300": { state: "Terengganu", district: "Kuala Terengganu" },
  "20400": { state: "Terengganu", district: "Kuala Terengganu" },
  "20500": { state: "Terengganu", district: "Kuala Terengganu" },
  "21000": { state: "Terengganu", district: "Kemaman" },
  "21050": { state: "Terengganu", district: "Kemaman" },
  "22000": { state: "Terengganu", district: "Dungun" },
  "23000": { state: "Terengganu", district: "Kuantan" },

  // Pahang
  "25000": { state: "Pahang", district: "Kuantan" },
  "25100": { state: "Pahang", district: "Kuantan" },
  "25150": { state: "Pahang", district: "Kuantan" },
  "25160": { state: "Pahang", district: "Kuantan" },
  "25170": { state: "Pahang", district: "Kuantan" },
  "25200": { state: "Pahang", district: "Kuantan" },
  "25250": { state: "Pahang", district: "Kuantan" },
  "25300": { state: "Pahang", district: "Kuantan" },
  "25350": { state: "Pahang", district: "Kuantan" },
  "25400": { state: "Pahang", district: "Kuantan" },
  "26000": { state: "Pahang", district: "Intan" },
  "26600": { state: "Pahang", district: "Pekan" },
  "27000": { state: "Pahang", district: "Temerloh" },
  "27100": { state: "Pahang", district: "Temerloh" },
  "27200": { state: "Pahang", district: "Temerloh" },
  "28000": { state: "Pahang", district: "Bentong" },
  "28800": { state: "Pahang", district: "Raub" },

  // Negeri Sembilan
  "70000": { state: "Negeri Sembilan", district: "Seremban" },
  "70100": { state: "Negeri Sembilan", district: "Seremban" },
  "70200": { state: "Negeri Sembilan", district: "Seremban" },
  "70300": { state: "Negeri Sembilan", district: "Seremban" },
  "70400": { state: "Negeri Sembilan", district: "Seremban" },
  "70500": { state: "Negeri Sembilan", district: "Seremban" },
  "70600": { state: "Negeri Sembilan", district: "Seremban" },
  "70700": { state: "Negeri Sembilan", district: "Seremban" },
  "70800": { state: "Negeri Sembilan", district: "Seremban" },
  "71000": { state: "Negeri Sembilan", district: "Muar" },
  "72000": { state: "Negeri Sembilan", district: "Kuala Pilah" },
  "73000": { state: "Negeri Sembilan", district: "Tampin" },

  // Melaka
  "75000": { state: "Melaka", district: "Malacca City" },
  "75050": { state: "Melaka", district: "Malacca City" },
  "75100": { state: "Melaka", district: "Malacca City" },
  "75200": { state: "Melaka", district: "Malacca City" },
  "75250": { state: "Melaka", district: "Malacca City" },
  "75260": { state: "Melaka", district: "Malacca City" },
  "75300": { state: "Melaka", district: "Malacca City" },
  "75400": { state: "Melaka", district: "Malacca City" },
  "75450": { state: "Melaka", district: "Malacca City" },
  "75500": { state: "Melaka", district: "Malacca City" },
  "76000": { state: "Melaka", district: "Ayer Keroh" },
  "76100": { state: "Melaka", district: "Ayer Keroh" },
  "76200": { state: "Melaka", district: "Ayer Keroh" },
  "77000": { state: "Melaka", district: "Jasin" },
  "78000": { state: "Melaka", district: "Alor Gajah" },

  // Labuan (Federal Territory)
  "87000": { state: "Labuan", district: "Labuan" },
  "87033": { state: "Labuan", district: "Labuan" },
  "88000": { state: "Sabah", district: "Kota Kinabalu" },
  "88100": { state: "Sabah", district: "Kota Kinabalu" },
  "88200": { state: "Sabah", district: "Kota Kinabalu" },
  "88300": { state: "Sabah", district: "Kota Kinabalu" },
  "88400": { state: "Sabah", district: "Kota Kinabalu" },
  "88500": { state: "Sabah", district: "Kota Kinabalu" },
  "88600": { state: "Sabah", district: "Penampang" },
  "88700": { state: "Sabah", district: "Penampang" },
  "88800": { state: "Sabah", district: "Sandakan" },
  "88900": { state: "Sabah", district: "Sandakan" },
  "89000": { state: "Sabah", district: "Tawau" },

  // Sarawak
  "93000": { state: "Sarawak", district: "Kuching" },
  "93100": { state: "Sarawak", district: "Kuching" },
  "93200": { state: "Sarawak", district: "Kuching" },
  "93300": { state: "Sarawak", district: "Kuching" },
  "93400": { state: "Sarawak", district: "Kuching" },
  "93500": { state: "Sarawak", district: "Kuching" },
  "93600": { state: "Sarawak", district: "Kuching" },
  "93700": { state: "Sarawak", district: "Kuching" },
  "93800": { state: "Sarawak", district: "Kuching" },
  "93900": { state: "Sarawak", district: "Kuching" },
  "94000": { state: "Sarawak", district: "Sibu" },
  "94100": { state: "Sarawak", district: "Sibu" },
  "94300": { state: "Sarawak", district: "Miri" },
  "97000": { state: "Sarawak", district: "Bintulu" },
};

export const getLocationFromPostcode = (
  postcode: string
): { state: string; district: string } | null => {
  const trimmedPostcode = postcode.trim();
  return MALAYSIAN_POSTCODE_MAP[trimmedPostcode] || null;
};

export const formatICNumber = (value: string): string => {
  // Remove all non-digits
  const cleaned = value.replace(/\D/g, "");
  
  // Apply format: xxxxxx-xx-xxxx
  if (cleaned.length <= 6) {
    return cleaned;
  } else if (cleaned.length <= 8) {
    return cleaned.slice(0, 6) + "-" + cleaned.slice(6);
  } else {
    return cleaned.slice(0, 6) + "-" + cleaned.slice(6, 8) + "-" + cleaned.slice(8, 12);
  }
};

export const formatPhoneNumber = (value: string): string => {
  // Keep only digits
  return value.replace(/\D/g, "");
};
