// src/features/Admin/Pages/Manage User/Register/components/pagetwoform.tsx
import React from "react";
import { Form, Row, Col } from "react-bootstrap";
import CustomDropdown from "./Option";

type Role = "admin" | "junioradmin" | "lawyer" | "client";

type Page2FormProps = {
  username: string;
  setUsername: (val: string) => void;
  email: string;
  setEmail: (val: string) => void;
  role: Role | "";
  setRole: (val: Role) => void;
  picture: File | null;
  setPicture: (file: File | null) => void;
  errors: {
    username?: string;
    email?: string;
    role?: string;
    picture?: string;
  };
};

const Page2Form: React.FC<Page2FormProps> = ({
  username,
  setUsername,
  email,
  setEmail,
  role,
  setRole,
  picture,
  setPicture,
  errors,
}) => {
  return (
    <Form className="admin-register-user-form">
      <div className="admin-register-user-form-section-title">Account and Access</div>
      <Row className="mb-3">
        <Col md={6}>
          <Form.Group controlId="formUsername">
            <Form.Label>Username <span className="text-danger">*</span></Form.Label>
            <Form.Control
              type="text"
              placeholder="Enter username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              isInvalid={!!errors.username}
            />
            <Form.Control.Feedback type="invalid">{errors.username}</Form.Control.Feedback>
          </Form.Group>
        </Col>

        <Col md={6}>
          <Form.Group controlId="formPasswordAutoGenerated">
            <Form.Label>Password</Form.Label>
            <Form.Control type="text" value="Auto-generated by system" disabled />
            <Form.Text className="text-muted">
              A temporary password will be generated automatically and sent to the user email.
            </Form.Text>
          </Form.Group>
        </Col>
      </Row>

      <Row className="mb-3">
        <Col md={6}>
          <Form.Group controlId="formEmail">
            <Form.Label>Email <span className="text-danger">*</span></Form.Label>
            <Form.Control
              type="email"
              placeholder="Enter email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              isInvalid={!!errors.email}
            />
            <Form.Control.Feedback type="invalid">{errors.email}</Form.Control.Feedback>
          </Form.Group>
        </Col>

        <Col md={6}>
          <Form.Group controlId="formRole">
            <Form.Label>Role <span className="text-danger">*</span></Form.Label>
            <CustomDropdown
              title={role || "Select role"}
              options={[
                { label: "Admin", value: "admin" },
                { label: "Junior Admin", value: "junioradmin" },
                { label: "Lawyer", value: "lawyer" },
                { label: "Client", value: "client" },
              ]}
              onSelect={(val) => setRole(val as Role)}
            />
            {errors.role && <div className="text-danger small mt-1">{errors.role}</div>}
          </Form.Group>
        </Col>
      </Row>

      <Row className="mb-3">
        <Col md={6}>
          <Form.Group controlId="formPassportPicture">
            <Form.Label>Passport Picture <span className="text-danger">*</span></Form.Label>
            <Form.Control
              type="file"
              accept="image/png,image/jpeg"
              required
              isInvalid={!!errors.picture}
              onChange={(e) => {
                const input = e.target as HTMLInputElement;
                setPicture(input.files?.[0] || null);
              }}
            />
            <Form.Control.Feedback type="invalid">{errors.picture}</Form.Control.Feedback>
            <Form.Text className="text-muted">
              Upload JPG/PNG passport-size photo (35:45 ratio, min 350x450, max 2MB).
            </Form.Text>
            {picture && (
              <div className="mt-2 small text-success">Selected: {picture.name}</div>
            )}
          </Form.Group>
        </Col>
      </Row>
    </Form>
  );
};

export default Page2Form;